name: Watt Trader application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          cd api
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          cd api
          pip install flake8
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          cd api
          pip install pytest
          pip install pytest-cov
          python -m pytest --cov-report=xml --cov=watt_trader tests
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./api/coverage.xml
          flags: unittests
          fail_ci_if_error: true
      - name: Deploy api
        uses: appleboy/scp-action@v0.0.5
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          source: "api"
          target: "staging/watt-trader"
      - name: Frontend
        run: |
          cd frontend
          yarn install
          yarn build
      - name: Deploy frontend
        uses: appleboy/scp-action@v0.0.5
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          source: "frontend/build"
          target: "staging/watt-trader/frontend"
